### ISSUE TITLE
Datahike server does not start. Most likely an issue with Konserve.

### ISSUE THREAD

**Issue by grischoun** [replikativ/datahike#156]
On the 'admin-endpoints' branch at startup time Datahike server throws the following error:

```
Caused by: java.lang.ClassNotFoundException: clojure.core.async.Mutex
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2207)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2220)
	at clojure.core.async.impl.mutex$loading__6706__auto____710.invoke(mutex.clj:9)
	at clojure.core.async.impl.mutex__init.load(Unknown Source)
	at clojure.core.async.impl.mutex__init.<clinit>(Unknown Source)
	... 211 more

```

I suspect an issue related to Konserve as when I install Konserve locally and reference its source code directly from Datahike server (instead of importing as a dependency), it works.

The current dependencies are:
```
[io.replikativ/datahike "0.2.2-SNAPSHOT"]
[io.replikativ/konserve "0.5.1"]

```

**Comment by kordano** [comment]
This issue should be moved to datahike-server if it's still relevant.
